from typing import Protocol


# Визначає мінімальний контракт для будь-якого способу зв'язку з пристроєм.
class Transport(Protocol):
    def open(self) -> None: ...

    def close(self) -> None: ...

    def send_line(self, line: str) -> None: ...

    def read_line(self, timeout: float) -> bytes | None: ...
